apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: api
        image: my-placeholder-user/python-devops-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "Production-GitOps"