apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-deployment.yaml
  - api-service.yaml
  - postgres-db.yaml

images:
  - name: my-placeholder-user/python-devops-api  # Must match the image in deployment.yaml
    newTag: latest